---
# tasks file for base_software
 - name: Update all packages
   zypper:
    name: '*'
    state: latest
    update_cache: yes
 
 - name: Install base packages
   zypper:
    name: "{{base_packages}}"

 - name: create key directory
   file:
        path: /home/pi/.ssh
        state: directory

 - name: upload user key
   copy:
        src: authorized_keys
        dest: /home/Adrixan/.ssh/authorized_keys

 - name: sshd configuration file update
   template:
        src: sshd_config
        dest: /etc/ssh/sshd_config
        backup: yes
        owner: 0
        group: 0
        mode: 0644
        validate: '/usr/sbin/sshd -T -f %s'

 - name: restart sshd
   systemd:
        name: sshd
        enabled: yes
        state: restarted
