---
- hosts: opensuse-servers
  remote_user: Adrixan
  become: yes
  roles:
     - base_software
     - shell_environment
     - { role: shell_environment, tags: shell_environment }
     - syncthing-daemon
     - { role: syncthing-daemon, tags: syncthing-daemon }
#     - docker-pi-hole
#     - { role: docker-pi-hole, tags: docker-pi-hole }
     - docker-sickgear
     - { role: docker-sickgear, tags: docker-sickgear }
     - docker-jackett
     - { role: docker-jackett, tags: docker-jackett }
     - docker-radarr
     - { role: docker-radarr, tags: docker-radarr }
     - plex-server
     - { role: plex-server, tags: plex-server}
#     - irc-bouncer
#     - { role: irc-bouncer, tags: irc-bouncer }
     - transmission-daemon
     - { role: transmission-daemon, tags: transmission-daemon }
     - rclone-backup
     - { role: rclone-backup, tags: rclone-backup }
     - graphical-environment
     - { role: graphical-environment, tags: graphical-environment }
     - rdp-server
     - { role: rdp-server, tags: rdp-server }
     - docker-bitwardenrs
     - { role: docker-bitwardenrs, tags: docker-bitwardenrs }

