---
# tasks file for desktop_messaging
- name: Add Signal repository
  community.general.zypper_repository:
    name: signal
    repo: 'https://download.opensuse.org/repositories/network:im:signal/openSUSE_Tumbleweed/'
    state: present
    auto_import_keys: yes

- name: Install Signal desktop client
  community.general.zypper:
    name: "{{ messaging_packages }}"
    state: present
    update_cache: yes
