---
# tasks file for docker-pi-hole
 - name: Create a directory if it does not exist
   file:
    path: /etc/docker-compose/jackett
    state: directory
    mode: '0755'

 - name: Create data directory if it does not exist
   file:
    path: /etc/docker-compose/jackett/data
    state: directory
    mode: '0755'

 - name: Create Jackett directory if it does not exist
   file:
    path: /etc/docker-compose/jackett/data/Jackett
    state: directory
    mode: '0755'

- name: copy ServerConfig.json
   copy:
    src: ServerConfig.json
    dest: /etc/docker-compose/jackett/data/Jackett
    mode: u+rwx,g+rx
 
 - name: copy nginx config
   copy:
    src: ja.conf
    dest: /etc/nginx/vhosts.d
    mode: u+rwx,g+rx

 - name: upload jackett docker-compose script
   template:
    src: docker-compose.yml
    dest: /etc/docker-compose/jackett/docker-compose.yml

 - name: Add recurring task for docker-compose refresh
   cron:
    name: "docker-compose-refresh"
    minute: "0"
    hour: "4"
    job: "/bin/systemctl reload docker-compose@*.service"

 - name: start jackett
   systemd:
    name: docker-compose@jackett
    state: started
    enabled: yes

