---
# tasks file for cli_tools
- name: Install build tool dependencies
  community.general.zypper:
    name: "{{ build_packages }}"
    state: present

- name: Install global npm CLI tools
  community.general.npm:
    name: "{{ item }}"
    global: yes
  loop: "{{ npm_global_packages }}"

- name: Install pip CLI tools
  ansible.builtin.pip:
    name: "{{ item }}"
    extra_args: "--break-system-packages"
  loop: "{{ pip_cli_packages }}"

- name: Clone tintin++ repository
  ansible.builtin.git:
    repo: 'https://github.com/scandum/tintin.git'
    dest: /tmp/tintin

- name: Build and install tintin++
  ansible.builtin.shell: ./configure && make && make install
  args:
    chdir: /tmp/tintin/src
    creates: /usr/local/bin/tt++
  when: not ansible_check_mode
